Steps:
  - Run: |
      echo "🔧 Updating system and installing Java"
      sudo yum update -y
      sudo yum install -y java-17-openjdk-devel git wget unzip

      echo "📁 Checking workspace contents"
      cd $AWS_WORKSPACE_PATH
      ls -l
      echo "📂 Listing lib folder"
      ls -l lib

      echo "🛠️ Compiling Java code"
      javac -cp "lib/*" TodoList.java todolist17Test.java || { echo '❌ Compilation failed'; exit 1; }

      echo "🚀 Running JUnit tests"
      java -jar lib/junit-platform-console-standalone-1.10.0.jar \
        -cp . --scan-classpath || { echo '❌ Tests failed'; exit 1; }

      echo "✅ Workflow completed successfully"

