Name: JavaJunitNoMaven
SchemaVersion: "1.0"

Triggers:
  - Type: PUSH
    Branches:
      - main

Actions:
  BuildAndTest:
    Identifier: aws/build@v1
    Inputs:
      Sources:
        - WorkflowSource
    Compute:
      Type: EC2
    Configuration:
      Steps:
        - Run: |
            echo "🔧 Installing Java and tools"
            sudo yum update -y
            sudo yum install -y java-17-openjdk-devel git wget unzip

            echo "📁 Navigating to workspace"
            cd $AWS_WORKSPACE_PATH

            echo "📂 Listing workspace contents"
            ls -l
            ls -l lib || echo "⚠️ lib folder not found"

            echo "🛠️ Compiling Java files"
            javac -cp "lib/*" TodoList.java todolist17Test.java || { echo '❌ Compilation failed'; exit 1; }

            echo "🚀 Running JUnit tests"
            java -jar lib/junit-platform-console-standalone-1.10.0.jar --class-path . --scan-classpath || { echo '❌ Tests failed'; exit 1; }

            echo "✅ Build and test completed successfully!"
