Name: JavaJUnitNoMaven
SchemaVersion: "1.0"

Triggers:
  - Type: PUSH
    Branches:
      - main

Actions:
  BuildAndTest:
    Identifier: aws/build@v1
    Inputs:
      Sources:
        - WorkflowSource
    Compute:
      Type: EC2
    Configuration:
      Steps:
        - Run: |
            echo "🔧 Installing Java and tools"
            sudo yum update -y
            sudo yum install -y java-17-openjdk-devel git wget unzip

            echo "📁 Navigating to repo"
            cd $AWS_WORKSPACE_PATH

            echo "📂 Contents:"
            ls -l

            echo "🛠️ Compiling Java files"
            javac -cp "lib/*" TodoList.java todolist17Test.java || { echo "❌ Compilation failed"; exit 1; }

            echo "🚀 Running tests"
            java -jar lib/junit-platform-console-standalone-1.10.0.jar -cp . --scan-classpath || { echo "❌ Tests failed"; exit 1; }

            echo "✅ All steps completed successfully!"
