Name: JavaJUnitNoMaven
SchemaVersion: "1.0"

Triggers:
  - Type: PUSH
    Branches:
      - main

Actions:
  BuildAndTest:
    Identifier: aws/build@v1
    Inputs:
      Sources:
        - WorkflowSource
    Compute:
      Type: EC2
    Configuration:
      Steps:
        - Run: |
            echo "🕵️ Step 1: Investigating File System"
            echo "💡 \$AWS_WORKSPACE_PATH = $AWS_WORKSPACE_PATH"

            echo "📁 Listing contents of workspace:"
            ls -l $AWS_WORKSPACE_PATH || echo "❌ Workspace path is empty"

            echo "📂 Finding all .java files in system:"
            find / -type f -name "*.java" 2>/dev/null

            echo "📂 Finding all lib folders:"
            find / -type d -name "lib" 2>/dev/null

            echo "📁 Finding all files named junit-platform-console-standalone-1.10.0.jar:"
            find / -type f -name "junit-platform-console-standalone-1.10.0.jar" 2>/dev/null

            echo "📦 Dumping entire folder structure (3 levels deep):"
            find / -maxdepth 3 -type d 2>/dev/null
