Name: JavaJUnitNoMaven
SchemaVersion: 1.0

Triggers:
  - Type: PUSH
    Branches:
      - main

Actions:
  BuildAndTest:
    Identifier: aws/build@v1
    Inputs:
      Sources:
        - WorkflowSource
    Compute:
      Type: EC2
    Configuration:
      Steps:
        - Run: |
            echo "🔧 Step 1: Installing Java"
            sudo yum update -y
            sudo yum install -y java-17-openjdk-devel git wget unzip

            echo "📁 Step 2: Navigating to workspace"
            cd $AWS_WORKSPACE_PATH
            echo "📦 Current files:"
            ls -l

            echo "
