Name: JavaJUnitNoMaven
SchemaVersion: 1.0

Triggers:
  - Type: PUSH
    Branches:
      - main

Actions:
  BuildAndTest:
    Identifier: aws/build@v1
    Inputs:
      Sources:
        - WorkflowSource
    Compute:
      Type: EC2
    Configuration:
      Steps:
        - Name: Install Java and tools
          Run: |
            sudo yum update -y
            sudo yum install -y java-17-openjdk-devel git wget unzip

        - Name: List workspace contents
          Run: |
            cd $AWS_WORKSPACE_PATH
            ls -l
            ls -l lib

        - Name: Compile Java files
          Run: |
            cd $AWS_WORKSPACE_PATH
            javac -cp "lib/*" TodoList.java todolist17Test.java || { echo '❌ Compilation failed'; exit 1; }

        - Name: Run JUnit tests
          Run: |
            cd $AWS_WORKSPACE_PATH
            java -jar lib/junit-platform-console-standalone-1.10.0.jar \
              -cp . --scan-classpath || { echo '❌ Tests failed'; exit 1; }

        - Name: Done!
          Run: echo "✅ CI complete!"
